services:
  - type: web
    name: stock-market-prediction
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install numpy==1.24.3
      pip install scipy==1.10.1
      pip install -r requirements.txt
    startCommand: gunicorn app:server